export const ACTION = "ACTION";

export const TENSION = "TENSION";
export const PERSONAL = {};
export const MYSTERY = ""; 
export const SOCIAL = {};


export const CHOOSE_MOST_LOGICAL_PLOTLINE = "Choose Most Logical Plotline";
export const NEW_PLOTLINE = "NEW PLOTLINE";

export const priorityTable = (
    firstPriority: string= "",
    secondPriority: string= "",
    thirdPriority: string= "",
    fourthPriority: string= "",
    fifthPriority: string= "",
) => ({ 
    1: firstPriority,
    2: secondPriority,
    3: thirdPriority,
    4: fourthPriority,
    5: fifthPriority 
});

export const defaultPlotLineTable = (
    {
    "1": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "2": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "3": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "4": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "5": NEW_PLOTLINE,
    "6": NEW_PLOTLINE,
    "7": NEW_PLOTLINE,
    "8": NEW_PLOTLINE,
    "9": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "10": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "11": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "12": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "13": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "14": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "15": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "16": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "17": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "18": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "19": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "20": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "21": NEW_PLOTLINE,
    "22": NEW_PLOTLINE,
    "23": NEW_PLOTLINE,
    "24": NEW_PLOTLINE,
    "25": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "26": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "27": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "28": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "29": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "30": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "31": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "32": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "33": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "34": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "35": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "36": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "37": NEW_PLOTLINE,
    "38": NEW_PLOTLINE,
    "39": NEW_PLOTLINE,
    "40": NEW_PLOTLINE,
    "41": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "42": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "43": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "44": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "45": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "46": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "47": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "48": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "49": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "50": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "51": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "52": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "53": NEW_PLOTLINE,
    "54": NEW_PLOTLINE,
    "55": NEW_PLOTLINE,
    "56": NEW_PLOTLINE,
    "57": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "58": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "59": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "60": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "61": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "62": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "63": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "64": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "65": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "66": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "67": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "68": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "69": NEW_PLOTLINE,
    "70": NEW_PLOTLINE,
    "71": NEW_PLOTLINE,
    "72": NEW_PLOTLINE,
    "73": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "74": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "75": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "76": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "77": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "78": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "79": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "80": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "81": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "82": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "83": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "84": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "85": NEW_PLOTLINE,
    "86": NEW_PLOTLINE,
    "87": NEW_PLOTLINE,
    "88": NEW_PLOTLINE,
    "89": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "90": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "91": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "92": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "93": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "94": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "95": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "96": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "97": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "98": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "99": CHOOSE_MOST_LOGICAL_PLOTLINE,
    "100": CHOOSE_MOST_LOGICAL_PLOTLINE
});

export const defaultCharacterTable = ({
    "1": "Value",
    "2": "Value",
    "3": "Value",
    "4": "Value",
    "5": "Value",
    "6": "Value",
    "7": "Value",
    "8": "Value",
    "9": "Value",
    "10": "Value",
    "11": "Value",
    "12": "Value",
    "13": "Value",
    "14": "Value",
    "15": "Value",
    "16": "Value",
    "17": "Value",
    "18": "Value",
    "19": "Value",
    "20": "Value",
    "21": "Value",
    "22": "Value",
    "23": "Value",
    "24": "Value",
    "25": "Value",
    "26": "Value",
    "27": "Value",
    "28": "Value",
    "29": "Value",
    "30": "Value",
    "31": "Value",
    "32": "Value",
    "33": "Value",
    "34": "Value",
    "35": "Value",
    "36": "Value",
    "37": "Value",
    "38": "Value",
    "39": "Value",
    "40": "Value",
    "41": "Value",
    "42": "Value",
    "43": "Value",
    "44": "Value",
    "45": "Value",
    "46": "Value",
    "47": "Value",
    "48": "Value",
    "49": "Value",
    "50": "Value",
    "51": "Value",
    "52": "Value",
    "53": "Value",
    "54": "Value",
    "55": "Value",
    "56": "Value",
    "57": "Value",
    "58": "Value",
    "59": "Value",
    "60": "Value",
    "61": "Value",
    "62": "Value",
    "63": "Value",
    "64": "Value",
    "65": "Value",
    "66": "Value",
    "67": "Value",
    "68": "Value",
    "69": "Value",
    "70": "Value",
    "71": "Value",
    "72": "Value",
    "73": "Value",
    "74": "Value",
    "75": "Value",
    "76": "Value",
    "77": "Value",
    "78": "Value",
    "79": "Value",
    "80": "Value",
    "81": "Value",
    "82": "Value",
    "83": "Value",
    "84": "Value",
    "85": "Value",
    "86": "Value",
    "87": "Value",
    "88": "Value",
    "89": "Value",
    "90": "Value",
    "91": "Value",
    "92": "Value",
    "93": "Value",
    "94": "Value",
    "95": "Value",
    "96": "Value",
    "97": "Value",
    "98": "Value",
    "99": "Value",
    "100": "Value"
});