import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ReactQueryClientProvider, UserProvider } from "./providers";
import { createClient } from "@/utils/supabase/server";
import Header from "./header";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
 const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser()
  return (
    <ReactQueryClientProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
            <UserProvider initialUser={user}>
              <Header/>
              <main className="max-w-7xl mx-auto p-4">{children}</main>
              </UserProvider>
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}
